In [265]:
# Importing Libraries 
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
import warnings

In [266]:
train=pd.read_csv('train.csv/train.csv')
test=pd.read_csv('test.csv/test.csv')

In [267]:
train.head()

id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [268]:
test.head()

id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...

In [269]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31962 entries, 0 to 31961
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      31962 non-null  int64 
 1   label   31962 non-null  int64 
 2   tweet   31962 non-null  object
dtypes: int64(2), object(1)
memory usage: 749.2+ KB


In [270]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17197 entries, 0 to 17196
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      17197 non-null  int64 
 1   tweet   17197 non-null  object
dtypes: int64(1), object(1)
memory usage: 268.8+ KB


In [271]:
combine_df = train.append(test, ignore_index = True, sort = False)
combine_df.head()

id  label                                              tweet
0   1    0.0   @user when a father is dysfunctional and is s...
1   2    0.0  @user @user thanks for #lyft credit i can't us...
2   3    0.0                                bihday your majesty
3   4    0.0  #model   i love u take with u all the time in ...
4   5    0.0             factsguide: society now    #motivation

In [272]:
combine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49159 entries, 0 to 49158
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   id      49159 non-null  int64  
 1   label   31962 non-null  float64
 2   tweet   49159 non-null  object 
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ MB


In [273]:
from html.parser import HTMLParser
html_parser = HTMLParser()

In [274]:
train['clean_tweet'] = train['tweet'].apply(lambda x: html_parser.unescape(x))
train.head(10)

<ipython-input-274-7ce2db86600f>:1: DeprecationWarning: The unescape method is deprecated and will be removed in 3.5, use html.unescape() instead.
  train['clean_tweet'] = train['tweet'].apply(lambda x: html_parser.unescape(x))


id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                         clean_tweet  
0   @user when a father is dysfunctional and is s...  
1  @user @user thanks for #lyft credit i can't us...  
2                                bihday your majesty  
3  #model   i love u take with u all the time in ...  
4             factsguide: society now    #motivation  
5  [2/2] huge fan fare and big talking before the...  
6   @user camping tomorrow @user @user @user @use...  
7  the next school year is the year for exams.ðŸ˜...  
8  we won!!! love the land!!! #allin #cavs #champ...  
9   @user @user welcome here !  i'm   it's so #gr...

In [275]:
def remove_pattern(input_txt, pattern):
    r = re.findall(pattern, input_txt)
    for i in r:
        input_txt = re.sub(i, '', input_txt)
    return input_txt

In [276]:
# remove twitter handles (@user)
train['clean_tweet'] = np.vectorize(remove_pattern)(train['clean_tweet'], "@[\w]*")
train.head()

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   

                                         clean_tweet  
0    when a father is dysfunctional and is so sel...  
1    thanks for #lyft credit i can't use cause th...  
2                                bihday your majesty  
3  #model   i love u take with u all the time in ...  
4             factsguide: society now    #motivation

In [277]:
train['clean_tweet'] = train['clean_tweet'].apply(lambda x: x.lower())
train.head()

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   

                                         clean_tweet  
0    when a father is dysfunctional and is so sel...  
1    thanks for #lyft credit i can't use cause th...  
2                                bihday your majesty  
3  #model   i love u take with u all the time in ...  
4             factsguide: society now    #motivation

In [278]:
apostrophe_dict = {
"ain't": "am not / are not","aren't": "are not / am not","can't": "cannot","can't've": "cannot have","'cause": "because",
"could've": "could have","couldn't": "could not","couldn't've": "could not have","didn't": "did not","doesn't": "does not",
"don't": "do not","hadn't": "had not","hadn't've": "had not have","hasn't": "has not","haven't": "have not",
"he'd": "he had / he would","he'd've": "he would have","he'll": "he shall / he will",
"he'll've": "he shall have / he will have","he's": "he has / he is","how'd": "how did","how'd'y": "how do you",
"how'll": "how will","how's": "how has / how is","i'd": "I had / I would","i'd've": "I would have","i'll": "I shall / I will",
"i'll've": "I shall have / I will have","i'm": "I am","i've": "I have","isn't": "is not","it'd": "it had / it would",
"it'd've": "it would have","it'll": "it shall / it will","it'll've": "it shall have / it will have","it's": "it has / it is",
"let's": "let us","ma'am": "madam","mayn't": "may not","might've": "might have","mightn't": "might not",
"mightn't've": "might not have","must've": "must have","mustn't": "must not","mustn't've": "must not have",
"needn't": "need not","needn't've": "need not have","o'clock": "of the clock","oughtn't": "ought not",
"oughtn't've": "ought not have","shan't": "shall not","sha'n't": "shall not","shan't've": "shall not have",
"she'd": "she had / she would","she'd've": "she would have","she'll": "she shall / she will",
"she'll've": "she shall have / she will have","she's": "she has / she is","should've": "should have","shouldn't": "should not",
"shouldn't've": "should not have","so've": "so have","so's": "so as / so is","that'd": "that would / that had",
"that'd've": "that would have","that's": "that has / that is","there'd": "there had / there would",
"there'd've": "there would have","there's": "there has / there is","they'd": "they had / they would",
"they'd've": "they would have","they'll": "they shall / they will","they'll've": "they shall have / they will have",
"they're": "they are","they've": "they have","to've": "to have","wasn't": "was not","we'd": "we had / we would",
"we'd've": "we would have","we'll": "we will","we'll've": "we will have","we're": "we are","we've": "we have",
"weren't": "were not","what'll": "what shall / what will","what'll've": "what shall have / what will have",
"what're": "what are","what's": "what has / what is","what've": "what have","when's": "when has / when is",
"when've": "when have","where'd": "where did","where's": "where has / where is","where've": "where have",
"who'll": "who shall / who will","who'll've": "who shall have / who will have",
"who's": "who has / who is","who've": "who have","why's": "why has / why is","why've": "why have","will've": "will have",
"won't": "will not","won't've": "will not have","would've": "would have","wouldn't": "would not",
"wouldn't've": "would not have","y'all": "you all","y'all'd": "you all would","y'all'd've": "you all would have",
"y'all're": "you all are","y'all've": "you all have","you'd": "you had / you would","you'd've": "you would have",
"you'll": "you shall / you will","you'll've": "you shall have / you will have","you're": "you are","you've": "you have"}

In [279]:
def lookup_dict(text, dictionary):
    for word in text.split():
        if word.lower() in dictionary:
            if word.lower() in text.split():
                text = text.replace(word, dictionary[word.lower()])
    return text

In [280]:
train['clean_tweet'] = train['clean_tweet'].apply(lambda x: lookup_dict(x,apostrophe_dict))
train.head()

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   

                                         clean_tweet  
0    when a father is dysfunctional and is so sel...  
1    thanks for #lyft credit i cannot use cause t...  
2                                bihday your majesty  
3  #model   i love u take with u all the time in ...  
4             factsguide: society now    #motivation

In [281]:
train['clean_tweet'] = train['clean_tweet'].apply(lambda x: re.sub(r'[^\w\s]',' ',x))
train.head(10)

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                         clean_tweet  
0    when a father is dysfunctional and is so sel...  
1    thanks for  lyft credit i cannot use cause t...  
2                                bihday your majesty  
3   model   i love u take with u all the time in ...  
4             factsguide  society now     motivation  
5   2 2  huge fan fare and big talking before the...  
6                   camping tomorrow        dannyâ    
7  the next school year is the year for exams ð  ...  
8  we won    love the land     allin  cavs  champ...  
9     welcome here    I am   it has   it is so  g...

In [282]:
train['clean_tweet'] = train['clean_tweet'].apply(lambda x: re.sub(r'[^a-zA-Z0-9]',' ',x))
train.head(10)

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                         clean_tweet  
0    when a father is dysfunctional and is so sel...  
1    thanks for  lyft credit i cannot use cause t...  
2                                bihday your majesty  
3   model   i love u take with u all the time in ...  
4             factsguide  society now     motivation  
5   2 2  huge fan fare and big talking before the...  
6                   camping tomorrow        danny     
7  the next school year is the year for exams    ...  
8  we won    love the land     allin  cavs  champ...  
9     welcome here    I am   it has   it is so  g...

In [283]:
train.head(10)

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                         clean_tweet  
0    when a father is dysfunctional and is so sel...  
1    thanks for  lyft credit i cannot use cause t...  
2                                bihday your majesty  
3   model   i love u take with u all the time in ...  
4             factsguide  society now     motivation  
5   2 2  huge fan fare and big talking before the...  
6                   camping tomorrow        danny     
7  the next school year is the year for exams    ...  
8  we won    love the land     allin  cavs  champ...  
9     welcome here    I am   it has   it is so  g...

In [284]:
train['clean_tweet'] = train['clean_tweet'].apply(lambda x: re.sub(r'[^a-zA-Z]',' ',x))
train.head(10)

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                         clean_tweet  
0    when a father is dysfunctional and is so sel...  
1    thanks for  lyft credit i cannot use cause t...  
2                                bihday your majesty  
3   model   i love u take with u all the time in ...  
4             factsguide  society now     motivation  
5        huge fan fare and big talking before the...  
6                   camping tomorrow        danny     
7  the next school year is the year for exams    ...  
8  we won    love the land     allin  cavs  champ...  
9     welcome here    I am   it has   it is so  g...

In [285]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [286]:
# Creating token for the clean tweets
train ['tweet_token'] = train['clean_tweet'].apply(lambda x: word_tokenize(x))

## Fully formated tweets & there tokens
train.head(10)

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                         clean_tweet  \
0    when a father is dysfunctional and is so sel...   
1    thanks for  lyft credit i cannot use cause t...   
2                                bihday your majesty   
3   model   i love u take with u all the time in ...   
4             factsguide  society now     motivation   
5        huge fan fare and big talking before the...   
6                   camping tomorrow        danny      
7  the next school year is the year for exams    ...   
8  we won    love the land     allin  cavs  champ...   
9     welcome here    I am   it has   it is so  g...   

                                         tweet_token  
0  [when, a, father, is, dysfunctional, and, is, ...  
1  [thanks, for, lyft, credit, i, can, not, use, ...  
2                            [bihday, your, majesty]  
3  [model, i, love, u, take, with, u, all, the, t...  
4             [factsguide, society, now, motivation]  
5  [huge, fan, fare, and, big, talking, before, t...  
6                         [camping, tomorrow, danny]  
7  [the, next, school, year, is, the, year, for, ...  
8  [we, won, love, the, land, allin, cavs, champi...  
9    [welcome, here, I, am, it, has, it, is, so, gr]

In [287]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [288]:
# Created new columns of tokens - where stop words are being removed
train['tweet_token_filtered'] = train['tweet_token'].apply(lambda x: [word for word in x if not word in stop_words])

## Tokens columns with stop words and without stop words
train.head(10)

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                         clean_tweet  \
0    when a father is dysfunctional and is so sel...   
1    thanks for  lyft credit i cannot use cause t...   
2                                bihday your majesty   
3   model   i love u take with u all the time in ...   
4             factsguide  society now     motivation   
5        huge fan fare and big talking before the...   
6                   camping tomorrow        danny      
7  the next school year is the year for exams    ...   
8  we won    love the land     allin  cavs  champ...   
9     welcome here    I am   it has   it is so  g...   

                                         tweet_token  \
0  [when, a, father, is, dysfunctional, and, is, ...   
1  [thanks, for, lyft, credit, i, can, not, use, ...   
2                            [bihday, your, majesty]   
3  [model, i, love, u, take, with, u, all, the, t...   
4             [factsguide, society, now, motivation]   
5  [huge, fan, fare, and, big, talking, before, t...   
6                         [camping, tomorrow, danny]   
7  [the, next, school, year, is, the, year, for, ...   
8  [we, won, love, the, land, allin, cavs, champi...   
9    [welcome, here, I, am, it, has, it, is, so, gr]   

                                tweet_token_filtered  
0  [father, dysfunctional, selfish, drags, kids, ...  
1  [thanks, lyft, credit, use, cause, offer, whee...  
2                                  [bihday, majesty]  
3                [model, love, u, take, u, time, ur]  
4                  [factsguide, society, motivation]  
5  [huge, fan, fare, big, talking, leave, chaos, ...  
6                         [camping, tomorrow, danny]  
7  [next, school, year, year, exams, think, schoo...  
8  [love, land, allin, cavs, champions, cleveland...  
9                                   [welcome, I, gr]

In [289]:
# Importing library for stemming
from nltk.stem import PorterStemmer
stemming = PorterStemmer()

In [290]:
# Created one more columns tweet_stemmed it shows tweets' stemmed version
train['tweet_stemmed'] = train['tweet_token_filtered'].apply(lambda x: ' '.join([stemming.stem(i) for i in x]))
train.head(10)

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                         clean_tweet  \
0    when a father is dysfunctional and is so sel...   
1    thanks for  lyft credit i cannot use cause t...   
2                                bihday your majesty   
3   model   i love u take with u all the time in ...   
4             factsguide  society now     motivation   
5        huge fan fare and big talking before the...   
6                   camping tomorrow        danny      
7  the next school year is the year for exams    ...   
8  we won    love the land     allin  cavs  champ...   
9     welcome here    I am   it has   it is so  g...   

                                         tweet_token  \
0  [when, a, father, is, dysfunctional, and, is, ...   
1  [thanks, for, lyft, credit, i, can, not, use, ...   
2                            [bihday, your, majesty]   
3  [model, i, love, u, take, with, u, all, the, t...   
4             [factsguide, society, now, motivation]   
5  [huge, fan, fare, and, big, talking, before, t...   
6                         [camping, tomorrow, danny]   
7  [the, next, school, year, is, the, year, for, ...   
8  [we, won, love, the, land, allin, cavs, champi...   
9    [welcome, here, I, am, it, has, it, is, so, gr]   

                                tweet_token_filtered  \
0  [father, dysfunctional, selfish, drags, kids, ...   
1  [thanks, lyft, credit, use, cause, offer, whee...   
2                                  [bihday, majesty]   
3                [model, love, u, take, u, time, ur]   
4                  [factsguide, society, motivation]   
5  [huge, fan, fare, big, talking, leave, chaos, ...   
6                         [camping, tomorrow, danny]   
7  [next, school, year, year, exams, think, schoo...   
8  [love, land, allin, cavs, champions, cleveland...   
9                                   [welcome, I, gr]   

                                       tweet_stemmed  
0      father dysfunct selfish drag kid dysfunct run  
1  thank lyft credit use caus offer wheelchair va...  
2                                     bihday majesti  
3                        model love u take u time ur  
4                            factsguid societi motiv  
5  huge fan fare big talk leav chao pay disput ge...  
6                                camp tomorrow danni  
7  next school year year exam think school exam h...  
8  love land allin cav champion cleveland clevela...  
9                                        welcom i gr

In [291]:
train.head(10)

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                         clean_tweet  \
0    when a father is dysfunctional and is so sel...   
1    thanks for  lyft credit i cannot use cause t...   
2                                bihday your majesty   
3   model   i love u take with u all the time in ...   
4             factsguide  society now     motivation   
5        huge fan fare and big talking before the...   
6                   camping tomorrow        danny      
7  the next school year is the year for exams    ...   
8  we won    love the land     allin  cavs  champ...   
9     welcome here    I am   it has   it is so  g...   

                                         tweet_token  \
0  [when, a, father, is, dysfunctional, and, is, ...   
1  [thanks, for, lyft, credit, i, can, not, use, ...   
2                            [bihday, your, majesty]   
3  [model, i, love, u, take, with, u, all, the, t...   
4             [factsguide, society, now, motivation]   
5  [huge, fan, fare, and, big, talking, before, t...   
6                         [camping, tomorrow, danny]   
7  [the, next, school, year, is, the, year, for, ...   
8  [we, won, love, the, land, allin, cavs, champi...   
9    [welcome, here, I, am, it, has, it, is, so, gr]   

                                tweet_token_filtered  \
0  [father, dysfunctional, selfish, drags, kids, ...   
1  [thanks, lyft, credit, use, cause, offer, whee...   
2                                  [bihday, majesty]   
3                [model, love, u, take, u, time, ur]   
4                  [factsguide, society, motivation]   
5  [huge, fan, fare, big, talking, leave, chaos, ...   
6                         [camping, tomorrow, danny]   
7  [next, school, year, year, exams, think, schoo...   
8  [love, land, allin, cavs, champions, cleveland...   
9                                   [welcome, I, gr]   

                                       tweet_stemmed  
0      father dysfunct selfish drag kid dysfunct run  
1  thank lyft credit use caus offer wheelchair va...  
2                                     bihday majesti  
3                        model love u take u time ur  
4                            factsguid societi motiv  
5  huge fan fare big talk leav chao pay disput ge...  
6                                camp tomorrow danni  
7  next school year year exam think school exam h...  
8  love land allin cav champion cleveland clevela...  
9                                        welcom i gr

In [292]:
# Importing library for lemmatizing
from nltk.stem.wordnet import WordNetLemmatizer
lemmatizing = WordNetLemmatizer()

In [293]:
# Created one more columns tweet_lemmatized it shows tweets' lemmatized version
train['tweet_lemmatized'] = train['tweet_token_filtered'].apply(lambda x: ' '.join([lemmatizing.lemmatize(i) for i in x]))
train.head(10)

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                         clean_tweet  \
0    when a father is dysfunctional and is so sel...   
1    thanks for  lyft credit i cannot use cause t...   
2                                bihday your majesty   
3   model   i love u take with u all the time in ...   
4             factsguide  society now     motivation   
5        huge fan fare and big talking before the...   
6                   camping tomorrow        danny      
7  the next school year is the year for exams    ...   
8  we won    love the land     allin  cavs  champ...   
9     welcome here    I am   it has   it is so  g...   

                                         tweet_token  \
0  [when, a, father, is, dysfunctional, and, is, ...   
1  [thanks, for, lyft, credit, i, can, not, use, ...   
2                            [bihday, your, majesty]   
3  [model, i, love, u, take, with, u, all, the, t...   
4             [factsguide, society, now, motivation]   
5  [huge, fan, fare, and, big, talking, before, t...   
6                         [camping, tomorrow, danny]   
7  [the, next, school, year, is, the, year, for, ...   
8  [we, won, love, the, land, allin, cavs, champi...   
9    [welcome, here, I, am, it, has, it, is, so, gr]   

                                tweet_token_filtered  \
0  [father, dysfunctional, selfish, drags, kids, ...   
1  [thanks, lyft, credit, use, cause, offer, whee...   
2                                  [bihday, majesty]   
3                [model, love, u, take, u, time, ur]   
4                  [factsguide, society, motivation]   
5  [huge, fan, fare, big, talking, leave, chaos, ...   
6                         [camping, tomorrow, danny]   
7  [next, school, year, year, exams, think, schoo...   
8  [love, land, allin, cavs, champions, cleveland...   
9                                   [welcome, I, gr]   

                                       tweet_stemmed  \
0      father dysfunct selfish drag kid dysfunct run   
1  thank lyft credit use caus offer wheelchair va...   
2                                     bihday majesti   
3                        model love u take u time ur   
4                            factsguid societi motiv   
5  huge fan fare big talk leav chao pay disput ge...   
6                                camp tomorrow danni   
7  next school year year exam think school exam h...   
8  love land allin cav champion cleveland clevela...   
9                                        welcom i gr   

                                    tweet_lemmatized  
0  father dysfunctional selfish drag kid dysfunct...  
1  thanks lyft credit use cause offer wheelchair ...  
2                                     bihday majesty  
3                        model love u take u time ur  
4                      factsguide society motivation  
5  huge fan fare big talking leave chaos pay disp...  
6                             camping tomorrow danny  
7  next school year year exam think school exam h...  
8  love land allin cavs champion cleveland clevel...  
9                                       welcome I gr

In [294]:
# Importing library
from sklearn.feature_extraction.text import CountVectorizer
bow_vectorizer = CountVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words='english')
bow_vectorizer

CountVectorizer(max_df=0.9, max_features=1000, min_df=2, stop_words='english')

In [295]:
# bag-of-words feature matrix - For columns "combine_df['tweet_stemmed']"
trainbow_stem = bow_vectorizer.fit_transform(train['tweet_stemmed'])
trainbow_stem

<31962x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 132469 stored elements in Compressed Sparse Row format>

In [296]:
trainbow_stem.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [297]:
# bag-of-words feature matrix - For column - combine_df['tweet_lemmatized']
trainbow_lemm = bow_vectorizer.fit_transform(train['tweet_lemmatized'])
trainbow_lemm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [298]:
# Importing library
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words='english')
tfidf_vectorizer

TfidfVectorizer(max_df=0.9, max_features=1000, min_df=2, stop_words='english')

In [299]:
# TF-IDF feature matrix - For columns "combine_df['tweet_stemmed']"
traintfidf_stem = tfidf_vectorizer.fit_transform(train['tweet_stemmed'])
traintfidf_stem.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [300]:
# TF-IDF feature matrix - For columns "combine_df['tweet_lemmatized']"
traintfidf_lemm = tfidf_vectorizer.fit_transform(train['tweet_lemmatized'])
traintfidf_lemm.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

--------------------------------------------------------------------------------------------------------------------------------

In [301]:
test

id                                              tweet
0      31963  #studiolife #aislife #requires #passion #dedic...
1      31964   @user #white #supremacists want everyone to s...
2      31965  safe ways to heal your #acne!!    #altwaystohe...
3      31966  is the hp and the cursed child book up for res...
4      31967    3rd #bihday to my amazing, hilarious #nephew...
...      ...                                                ...
17192  49155  thought factory: left-right polarisation! #tru...
17193  49156  feeling like a mermaid 😘 #hairflip #neverre...
17194  49157  #hillary #campaigned today in #ohio((omg)) &am...
17195  49158  happy, at work conference: right mindset leads...
17196  49159  my   song "so glad" free download!  #shoegaze ...

[17197 rows x 2 columns]

In [302]:
test['clean_tweet'] = test['tweet'].apply(lambda x: html_parser.unescape(x))
test.head(10)

<ipython-input-302-1779c9591afc>:1: DeprecationWarning: The unescape method is deprecated and will be removed in 3.5, use html.unescape() instead.
  test['clean_tweet'] = test['tweet'].apply(lambda x: html_parser.unescape(x))


id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   
5  31968                        choose to be   :) #momtips    
6  31969  something inside me dies 💦💿✨  eyes nes...   
7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...   
8  31971   @user @user @user i will never understand why...   
9  31972  #delicious   #food #lovelife #capetown mannaep...   

                                         clean_tweet  
0  #studiolife #aislife #requires #passion #dedic...  
1   @user #white #supremacists want everyone to s...  
2  safe ways to heal your #acne!!    #altwaystohe...  
3  is the hp and the cursed child book up for res...  
4    3rd #bihday to my amazing, hilarious #nephew...  
5                        choose to be   :) #momtips   
6  something inside me dies 💦💿✨  eyes nes...  
7  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...  
8   @user @user @user i will never understand why...  
9  #delicious   #food #lovelife #capetown mannaep...

In [303]:
def remove_pattern(input_txt, pattern):
    r = re.findall(pattern, input_txt)
    for i in r:
        input_txt = re.sub(i, '', input_txt)
    return input_txt

In [304]:
# remove twitter handles (@user)
test['clean_tweet'] = np.vectorize(remove_pattern)(test['clean_tweet'], "@[\w]*")
test.head()

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   

                                         clean_tweet  
0  #studiolife #aislife #requires #passion #dedic...  
1    #white #supremacists want everyone to see th...  
2  safe ways to heal your #acne!!    #altwaystohe...  
3  is the hp and the cursed child book up for res...  
4    3rd #bihday to my amazing, hilarious #nephew...

In [305]:
test['clean_tweet'] = test['clean_tweet'].apply(lambda x: x.lower())
test.head(10)

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   
5  31968                        choose to be   :) #momtips    
6  31969  something inside me dies 💦💿✨  eyes nes...   
7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...   
8  31971   @user @user @user i will never understand why...   
9  31972  #delicious   #food #lovelife #capetown mannaep...   

                                         clean_tweet  
0  #studiolife #aislife #requires #passion #dedic...  
1    #white #supremacists want everyone to see th...  
2  safe ways to heal your #acne!!    #altwaystohe...  
3  is the hp and the cursed child book up for res...  
4    3rd #bihday to my amazing, hilarious #nephew...  
5                        choose to be   :) #momtips   
6  something inside me dies 💦💿✨  eyes nes...  
7  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...  
8      i will never understand why my dad left me...  
9  #delicious   #food #lovelife #capetown mannaep...

In [306]:
apostrophe_dict = {
"ain't": "am not / are not","aren't": "are not / am not","can't": "cannot","can't've": "cannot have","'cause": "because",
"could've": "could have","couldn't": "could not","couldn't've": "could not have","didn't": "did not","doesn't": "does not",
"don't": "do not","hadn't": "had not","hadn't've": "had not have","hasn't": "has not","haven't": "have not",
"he'd": "he had / he would","he'd've": "he would have","he'll": "he shall / he will",
"he'll've": "he shall have / he will have","he's": "he has / he is","how'd": "how did","how'd'y": "how do you",
"how'll": "how will","how's": "how has / how is","i'd": "I had / I would","i'd've": "I would have","i'll": "I shall / I will",
"i'll've": "I shall have / I will have","i'm": "I am","i've": "I have","isn't": "is not","it'd": "it had / it would",
"it'd've": "it would have","it'll": "it shall / it will","it'll've": "it shall have / it will have","it's": "it has / it is",
"let's": "let us","ma'am": "madam","mayn't": "may not","might've": "might have","mightn't": "might not",
"mightn't've": "might not have","must've": "must have","mustn't": "must not","mustn't've": "must not have",
"needn't": "need not","needn't've": "need not have","o'clock": "of the clock","oughtn't": "ought not",
"oughtn't've": "ought not have","shan't": "shall not","sha'n't": "shall not","shan't've": "shall not have",
"she'd": "she had / she would","she'd've": "she would have","she'll": "she shall / she will",
"she'll've": "she shall have / she will have","she's": "she has / she is","should've": "should have","shouldn't": "should not",
"shouldn't've": "should not have","so've": "so have","so's": "so as / so is","that'd": "that would / that had",
"that'd've": "that would have","that's": "that has / that is","there'd": "there had / there would",
"there'd've": "there would have","there's": "there has / there is","they'd": "they had / they would",
"they'd've": "they would have","they'll": "they shall / they will","they'll've": "they shall have / they will have",
"they're": "they are","they've": "they have","to've": "to have","wasn't": "was not","we'd": "we had / we would",
"we'd've": "we would have","we'll": "we will","we'll've": "we will have","we're": "we are","we've": "we have",
"weren't": "were not","what'll": "what shall / what will","what'll've": "what shall have / what will have",
"what're": "what are","what's": "what has / what is","what've": "what have","when's": "when has / when is",
"when've": "when have","where'd": "where did","where's": "where has / where is","where've": "where have",
"who'll": "who shall / who will","who'll've": "who shall have / who will have",
"who's": "who has / who is","who've": "who have","why's": "why has / why is","why've": "why have","will've": "will have",
"won't": "will not","won't've": "will not have","would've": "would have","wouldn't": "would not",
"wouldn't've": "would not have","y'all": "you all","y'all'd": "you all would","y'all'd've": "you all would have",
"y'all're": "you all are","y'all've": "you all have","you'd": "you had / you would","you'd've": "you would have",
"you'll": "you shall / you will","you'll've": "you shall have / you will have","you're": "you are","you've": "you have"}

In [307]:
def lookup_dict(text, dictionary):
    for word in text.split():
        if word.lower() in dictionary:
            if word.lower() in text.split():
                text = text.replace(word, dictionary[word.lower()])
    return text

In [308]:
test['clean_tweet'] = test['clean_tweet'].apply(lambda x: lookup_dict(x,apostrophe_dict))
test.head(10)

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   
5  31968                        choose to be   :) #momtips    
6  31969  something inside me dies 💦💿✨  eyes nes...   
7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...   
8  31971   @user @user @user i will never understand why...   
9  31972  #delicious   #food #lovelife #capetown mannaep...   

                                         clean_tweet  
0  #studiolife #aislife #requires #passion #dedic...  
1    #white #supremacists want everyone to see th...  
2  safe ways to heal your #acne!!    #altwaystohe...  
3  is the hp and the cursed child book up for res...  
4    3rd #bihday to my amazing, hilarious #nephew...  
5                        choose to be   :) #momtips   
6  something inside me dies 💦💿✨  eyes nes...  
7  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...  
8      i will never understand why my dad left me...  
9  #delicious   #food #lovelife #capetown mannaep...

In [313]:
test['clean_tweet'] = test['clean_tweet'].apply(lambda x: re.sub(r'[^\w\s]',' ',x))
test.head()

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   

                                         clean_tweet  
0   studiolife  aislife  requires  passion  dedic...  
1     white  supremacists want everyone to see th...  
2  safe ways to heal your  acne       altwaystohe...  
3  is the hp and the cursed child book up for res...  
4    3rd  bihday to my amazing  hilarious  nephew...

In [314]:
test['clean_tweet'] = test['clean_tweet'].apply(lambda x: re.sub(r'[^a-zA-Z0-9]',' ',x))
test.head(10)

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   
5  31968                        choose to be   :) #momtips    
6  31969  something inside me dies 💦💿✨  eyes nes...   
7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...   
8  31971   @user @user @user i will never understand why...   
9  31972  #delicious   #food #lovelife #capetown mannaep...   

                                         clean_tweet  
0   studiolife  aislife  requires  passion  dedic...  
1     white  supremacists want everyone to see th...  
2  safe ways to heal your  acne       altwaystohe...  
3  is the hp and the cursed child book up for res...  
4    3rd  bihday to my amazing  hilarious  nephew...  
5                     choose to be   happy  momtips   
6  something inside me dies              eyes nes...  
7   finished tattoo inked ink loveit             ...  
8      i will never understand why my dad left me...  
9   delicious    food  lovelife  capetown mannaep...

In [315]:
train.head(10)

id  label                                              tweet  \
0   1      0   @user when a father is dysfunctional and is s...   
1   2      0  @user @user thanks for #lyft credit i can't us...   
2   3      0                                bihday your majesty   
3   4      0  #model   i love u take with u all the time in ...   
4   5      0             factsguide: society now    #motivation   
5   6      0  [2/2] huge fan fare and big talking before the...   
6   7      0   @user camping tomorrow @user @user @user @use...   
7   8      0  the next school year is the year for exams.ðŸ˜...   
8   9      0  we won!!! love the land!!! #allin #cavs #champ...   
9  10      0   @user @user welcome here !  i'm   it's so #gr...   

                                         clean_tweet  \
0    when a father is dysfunctional and is so sel...   
1    thanks for  lyft credit i cannot use cause t...   
2                                bihday your majesty   
3   model   i love u take with u all the time in ...   
4             factsguide  society now     motivation   
5        huge fan fare and big talking before the...   
6                   camping tomorrow        danny      
7  the next school year is the year for exams    ...   
8  we won    love the land     allin  cavs  champ...   
9     welcome here    I am   it has   it is so  g...   

                                         tweet_token  \
0  [when, a, father, is, dysfunctional, and, is, ...   
1  [thanks, for, lyft, credit, i, can, not, use, ...   
2                            [bihday, your, majesty]   
3  [model, i, love, u, take, with, u, all, the, t...   
4             [factsguide, society, now, motivation]   
5  [huge, fan, fare, and, big, talking, before, t...   
6                         [camping, tomorrow, danny]   
7  [the, next, school, year, is, the, year, for, ...   
8  [we, won, love, the, land, allin, cavs, champi...   
9    [welcome, here, I, am, it, has, it, is, so, gr]   

                                tweet_token_filtered  \
0  [father, dysfunctional, selfish, drags, kids, ...   
1  [thanks, lyft, credit, use, cause, offer, whee...   
2                                  [bihday, majesty]   
3                [model, love, u, take, u, time, ur]   
4                  [factsguide, society, motivation]   
5  [huge, fan, fare, big, talking, leave, chaos, ...   
6                         [camping, tomorrow, danny]   
7  [next, school, year, year, exams, think, schoo...   
8  [love, land, allin, cavs, champions, cleveland...   
9                                   [welcome, I, gr]   

                                       tweet_stemmed  \
0      father dysfunct selfish drag kid dysfunct run   
1  thank lyft credit use caus offer wheelchair va...   
2                                     bihday majesti   
3                        model love u take u time ur   
4                            factsguid societi motiv   
5  huge fan fare big talk leav chao pay disput ge...   
6                                camp tomorrow danni   
7  next school year year exam think school exam h...   
8  love land allin cav champion cleveland clevela...   
9                                        welcom i gr   

                                    tweet_lemmatized  
0  father dysfunctional selfish drag kid dysfunct...  
1  thanks lyft credit use cause offer wheelchair ...  
2                                     bihday majesty  
3                        model love u take u time ur  
4                      factsguide society motivation  
5  huge fan fare big talking leave chaos pay disp...  
6                             camping tomorrow danny  
7  next school year year exam think school exam h...  
8  love land allin cavs champion cleveland clevel...  
9                                       welcome I gr

In [316]:
test['clean_tweet'] = test['clean_tweet'].apply(lambda x: re.sub(r'[^a-zA-Z]',' ',x))
test.head(10)

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   
5  31968                        choose to be   :) #momtips    
6  31969  something inside me dies 💦💿✨  eyes nes...   
7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...   
8  31971   @user @user @user i will never understand why...   
9  31972  #delicious   #food #lovelife #capetown mannaep...   

                                         clean_tweet  
0   studiolife  aislife  requires  passion  dedic...  
1     white  supremacists want everyone to see th...  
2  safe ways to heal your  acne       altwaystohe...  
3  is the hp and the cursed child book up for res...  
4     rd  bihday to my amazing  hilarious  nephew...  
5                     choose to be   happy  momtips   
6  something inside me dies              eyes nes...  
7   finished tattoo inked ink loveit             ...  
8      i will never understand why my dad left me...  
9   delicious    food  lovelife  capetown mannaep...

In [317]:
from textblob import TextBlob

In [318]:
text = train['clean_tweet'][0:10].apply(lambda x: str(TextBlob(x).correct()))
text

0      when a father is dysfunctional and is so sel...
1      thanks for  left credit i cannot use cause t...
2                                  midday your majesty
3     model   i love u take with u all the time in ...
4               factsguide  society now     motivation
5          huge fan fare and big talking before the...
6                     camping tomorrow        dandy   
7    the next school year is the year for exam     ...
8    we won    love the land     allen  caps  champ...
9       welcome here    I am   it has   it is so  g...
Name: clean_tweet, dtype: object

In [319]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [320]:
# Creating token for the clean tweets
test ['tweet_token'] = test['clean_tweet'].apply(lambda x: word_tokenize(x))

## Fully formated tweets & there tokens
test.head(10)

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   
5  31968                        choose to be   :) #momtips    
6  31969  something inside me dies 💦💿✨  eyes nes...   
7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...   
8  31971   @user @user @user i will never understand why...   
9  31972  #delicious   #food #lovelife #capetown mannaep...   

                                         clean_tweet  \
0   studiolife  aislife  requires  passion  dedic...   
1     white  supremacists want everyone to see th...   
2  safe ways to heal your  acne       altwaystohe...   
3  is the hp and the cursed child book up for res...   
4     rd  bihday to my amazing  hilarious  nephew...   
5                     choose to be   happy  momtips    
6  something inside me dies              eyes nes...   
7   finished tattoo inked ink loveit             ...   
8      i will never understand why my dad left me...   
9   delicious    food  lovelife  capetown mannaep...   

                                         tweet_token  
0  [studiolife, aislife, requires, passion, dedic...  
1  [white, supremacists, want, everyone, to, see,...  
2  [safe, ways, to, heal, your, acne, altwaystohe...  
3  [is, the, hp, and, the, cursed, child, book, u...  
4  [rd, bihday, to, my, amazing, hilarious, nephe...  
5                   [choose, to, be, happy, momtips]  
6  [something, inside, me, dies, eyes, ness, smok...  
7  [finished, tattoo, inked, ink, loveit, thanks,...  
8  [i, will, never, understand, why, my, dad, lef...  
9  [delicious, food, lovelife, capetown, mannaepi...

In [321]:
stop_words = set(stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [322]:
# Created new columns of tokens - where stop words are being removed
test['tweet_token_filtered'] = test['tweet_token'].apply(lambda x: [word for word in x if not word in stop_words])

## Tokens columns with stop words and without stop words
test[['tweet_token', 'tweet_token_filtered']].head(10)

tweet_token  \
0  [studiolife, aislife, requires, passion, dedic...   
1  [white, supremacists, want, everyone, to, see,...   
2  [safe, ways, to, heal, your, acne, altwaystohe...   
3  [is, the, hp, and, the, cursed, child, book, u...   
4  [rd, bihday, to, my, amazing, hilarious, nephe...   
5                   [choose, to, be, happy, momtips]   
6  [something, inside, me, dies, eyes, ness, smok...   
7  [finished, tattoo, inked, ink, loveit, thanks,...   
8  [i, will, never, understand, why, my, dad, lef...   
9  [delicious, food, lovelife, capetown, mannaepi...   

                                tweet_token_filtered  
0  [studiolife, aislife, requires, passion, dedic...  
1  [white, supremacists, want, everyone, see, new...  
2  [safe, ways, heal, acne, altwaystoheal, health...  
3  [hp, cursed, child, book, reservations, alread...  
4  [rd, bihday, amazing, hilarious, nephew, eli, ...  
5                           [choose, happy, momtips]  
6  [something, inside, dies, eyes, ness, smokeyey...  
7  [finished, tattoo, inked, ink, loveit, thanks,...  
8  [never, understand, dad, left, young, deep, in...  
9  [delicious, food, lovelife, capetown, mannaepi...

In [323]:
# Importing library for stemming
from nltk.stem import PorterStemmer
stemming = PorterStemmer()

In [324]:
# Created one more columns tweet_stemmed it shows tweets' stemmed version
test['tweet_stemmed'] = test['tweet_token_filtered'].apply(lambda x: ' '.join([stemming.stem(i) for i in x]))
test['tweet_stemmed'].head(10)

0    studiolif aislif requir passion dedic willpow ...
1     white supremacist want everyon see new bird movi
2            safe way heal acn altwaystoh healthi heal
3    hp curs child book reserv alreadi ye harrypott...
4    rd bihday amaz hilari nephew eli ahmir uncl da...
5                                   choos happi momtip
6    someth insid die eye ness smokeyey tire lone s...
7             finish tattoo ink ink loveit thank aleee
8       never understand dad left young deep inthefeel
9      delici food lovelif capetown mannaepicur restur
Name: tweet_stemmed, dtype: object

In [325]:
test.head(10)

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   
5  31968                        choose to be   :) #momtips    
6  31969  something inside me dies 💦💿✨  eyes nes...   
7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...   
8  31971   @user @user @user i will never understand why...   
9  31972  #delicious   #food #lovelife #capetown mannaep...   

                                         clean_tweet  \
0   studiolife  aislife  requires  passion  dedic...   
1     white  supremacists want everyone to see th...   
2  safe ways to heal your  acne       altwaystohe...   
3  is the hp and the cursed child book up for res...   
4     rd  bihday to my amazing  hilarious  nephew...   
5                     choose to be   happy  momtips    
6  something inside me dies              eyes nes...   
7   finished tattoo inked ink loveit             ...   
8      i will never understand why my dad left me...   
9   delicious    food  lovelife  capetown mannaep...   

                                         tweet_token  \
0  [studiolife, aislife, requires, passion, dedic...   
1  [white, supremacists, want, everyone, to, see,...   
2  [safe, ways, to, heal, your, acne, altwaystohe...   
3  [is, the, hp, and, the, cursed, child, book, u...   
4  [rd, bihday, to, my, amazing, hilarious, nephe...   
5                   [choose, to, be, happy, momtips]   
6  [something, inside, me, dies, eyes, ness, smok...   
7  [finished, tattoo, inked, ink, loveit, thanks,...   
8  [i, will, never, understand, why, my, dad, lef...   
9  [delicious, food, lovelife, capetown, mannaepi...   

                                tweet_token_filtered  \
0  [studiolife, aislife, requires, passion, dedic...   
1  [white, supremacists, want, everyone, see, new...   
2  [safe, ways, heal, acne, altwaystoheal, health...   
3  [hp, cursed, child, book, reservations, alread...   
4  [rd, bihday, amazing, hilarious, nephew, eli, ...   
5                           [choose, happy, momtips]   
6  [something, inside, dies, eyes, ness, smokeyey...   
7  [finished, tattoo, inked, ink, loveit, thanks,...   
8  [never, understand, dad, left, young, deep, in...   
9  [delicious, food, lovelife, capetown, mannaepi...   

                                       tweet_stemmed  
0  studiolif aislif requir passion dedic willpow ...  
1   white supremacist want everyon see new bird movi  
2          safe way heal acn altwaystoh healthi heal  
3  hp curs child book reserv alreadi ye harrypott...  
4  rd bihday amaz hilari nephew eli ahmir uncl da...  
5                                 choos happi momtip  
6  someth insid die eye ness smokeyey tire lone s...  
7           finish tattoo ink ink loveit thank aleee  
8     never understand dad left young deep inthefeel  
9    delici food lovelif capetown mannaepicur restur

In [326]:
# Importing library for lemmatizing
from nltk.stem.wordnet import WordNetLemmatizer
lemmatizing = WordNetLemmatizer()

In [327]:
# Created one more columns tweet_lemmatized it shows tweets' lemmatized version
test['tweet_lemmatized'] = test['tweet_token_filtered'].apply(lambda x: ' '.join([lemmatizing.lemmatize(i) for i in x]))
test.head(10)

id                                              tweet  \
0  31963  #studiolife #aislife #requires #passion #dedic...   
1  31964   @user #white #supremacists want everyone to s...   
2  31965  safe ways to heal your #acne!!    #altwaystohe...   
3  31966  is the hp and the cursed child book up for res...   
4  31967    3rd #bihday to my amazing, hilarious #nephew...   
5  31968                        choose to be   :) #momtips    
6  31969  something inside me dies 💦💿✨  eyes nes...   
7  31970  #finished#tattoo#inked#ink#loveit❤️ #❤ï¸...   
8  31971   @user @user @user i will never understand why...   
9  31972  #delicious   #food #lovelife #capetown mannaep...   

                                         clean_tweet  \
0   studiolife  aislife  requires  passion  dedic...   
1     white  supremacists want everyone to see th...   
2  safe ways to heal your  acne       altwaystohe...   
3  is the hp and the cursed child book up for res...   
4     rd  bihday to my amazing  hilarious  nephew...   
5                     choose to be   happy  momtips    
6  something inside me dies              eyes nes...   
7   finished tattoo inked ink loveit             ...   
8      i will never understand why my dad left me...   
9   delicious    food  lovelife  capetown mannaep...   

                                         tweet_token  \
0  [studiolife, aislife, requires, passion, dedic...   
1  [white, supremacists, want, everyone, to, see,...   
2  [safe, ways, to, heal, your, acne, altwaystohe...   
3  [is, the, hp, and, the, cursed, child, book, u...   
4  [rd, bihday, to, my, amazing, hilarious, nephe...   
5                   [choose, to, be, happy, momtips]   
6  [something, inside, me, dies, eyes, ness, smok...   
7  [finished, tattoo, inked, ink, loveit, thanks,...   
8  [i, will, never, understand, why, my, dad, lef...   
9  [delicious, food, lovelife, capetown, mannaepi...   

                                tweet_token_filtered  \
0  [studiolife, aislife, requires, passion, dedic...   
1  [white, supremacists, want, everyone, see, new...   
2  [safe, ways, heal, acne, altwaystoheal, health...   
3  [hp, cursed, child, book, reservations, alread...   
4  [rd, bihday, amazing, hilarious, nephew, eli, ...   
5                           [choose, happy, momtips]   
6  [something, inside, dies, eyes, ness, smokeyey...   
7  [finished, tattoo, inked, ink, loveit, thanks,...   
8  [never, understand, dad, left, young, deep, in...   
9  [delicious, food, lovelife, capetown, mannaepi...   

                                       tweet_stemmed  \
0  studiolif aislif requir passion dedic willpow ...   
1   white supremacist want everyon see new bird movi   
2          safe way heal acn altwaystoh healthi heal   
3  hp curs child book reserv alreadi ye harrypott...   
4  rd bihday amaz hilari nephew eli ahmir uncl da...   
5                                 choos happi momtip   
6  someth insid die eye ness smokeyey tire lone s...   
7           finish tattoo ink ink loveit thank aleee   
8     never understand dad left young deep inthefeel   
9    delici food lovelif capetown mannaepicur restur   

                                    tweet_lemmatized  
0  studiolife aislife requires passion dedication...  
1  white supremacist want everyone see new bird m...  
2   safe way heal acne altwaystoheal healthy healing  
3  hp cursed child book reservation already yes h...  
4  rd bihday amazing hilarious nephew eli ahmir u...  
5                               choose happy momtips  
6  something inside dy eye ness smokeyeyes tired ...  
7     finished tattoo inked ink loveit thanks aleeee  
8    never understand dad left young deep inthefeels  
9  delicious food lovelife capetown mannaepicure ...

In [328]:
# Importing library
from sklearn.feature_extraction.text import CountVectorizer
bow_vectorizer = CountVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words='english')
bow_vectorizer

CountVectorizer(max_df=0.9, max_features=1000, min_df=2, stop_words='english')

In [329]:
# bag-of-words feature matrix - For columns "combine_df['tweet_stemmed']"
testbow_stem = bow_vectorizer.fit_transform(test['tweet_stemmed'])
testbow_stem.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [330]:
# bag-of-words feature matrix - For column - combine_df['tweet_lemmatized']
testbow_lemm = bow_vectorizer.fit_transform(test['tweet_lemmatized'])
testbow_lemm.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [331]:
# Importing library
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(max_df=0.90, min_df=2, max_features=1000, stop_words='english')
tfidf_vectorizer

TfidfVectorizer(max_df=0.9, max_features=1000, min_df=2, stop_words='english')

In [332]:
# TF-IDF feature matrix - For columns "combine_df['tweet_stemmed']"
testtfidf_stem = tfidf_vectorizer.fit_transform(test['tweet_stemmed'])
testtfidf_stem.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [333]:
# TF-IDF feature matrix - For columns "combine_df['tweet_lemmatized']"
testtfidf_lemm = tfidf_vectorizer.fit_transform(test['tweet_lemmatized'])
testtfidf_lemm.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [334]:
train.drop(columns=['id','tweet','clean_tweet','tweet_token','tweet_token_filtered','tweet_stemmed'],axis=1,inplace=True)

In [335]:
test.drop(columns=['id','tweet','clean_tweet','tweet_token','tweet_token_filtered','tweet_stemmed'],axis=1,inplace=True)

In [336]:
# Importing Libraries
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [337]:
X=traintfidf_lemm
y=train['label']

In [338]:
xtrain,xtest,ytrain,ytest=train_test_split(X,y,test_size=.3,random_state=42)

In [339]:
lr=LogisticRegression()

In [340]:
lr.fit(xtrain,ytrain)

LogisticRegression()

In [341]:
predict_lr=lr.predict(xtest)

In [342]:
accuracy_score(predict_lr,ytest)

0.9468140577745333

In [343]:
print(confusion_matrix(predict_lr,ytest))
print(classification_report(predict_lr,ytest))

[[8855  460]
 [  50  224]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97      9315
           1       0.33      0.82      0.47       274

    accuracy                           0.95      9589
   macro avg       0.66      0.88      0.72      9589
weighted avg       0.98      0.95      0.96      9589



In [344]:
svc=SVC()

In [345]:
svc.fit(xtrain,ytrain)
predict_svc=svc.predict(xtest)

In [346]:
print(accuracy_score(predict_svc,ytest))
print(confusion_matrix(predict_svc,ytest))
print(classification_report(predict_svc,ytest))

0.948274064031703
[[8850  441]
 [  55  243]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97      9291
           1       0.36      0.82      0.49       298

    accuracy                           0.95      9589
   macro avg       0.67      0.88      0.73      9589
weighted avg       0.97      0.95      0.96      9589



In [347]:
nb=GaussianNB()

In [348]:
nb.fit(xtrain.toarray(),ytrain)
predict_nb=nb.predict(xtest.toarray())

In [349]:
print(accuracy_score(predict_nb,ytest))
print(confusion_matrix(predict_nb,ytest))
print(classification_report(predict_nb,ytest))

0.5796224840963604
[[4932   58]
 [3973  626]]
              precision    recall  f1-score   support

           0       0.55      0.99      0.71      4990
           1       0.92      0.14      0.24      4599

    accuracy                           0.58      9589
   macro avg       0.73      0.56      0.47      9589
weighted avg       0.73      0.58      0.48      9589



--------------------------------------------------------------------------------------------------------------------------------

In [350]:
X1=traintfidf_stem
y1=train['label']

In [351]:
x1train,x1test,y1train,y1test=train_test_split(X1,y1,test_size=.3,random_state=42)

In [352]:
lr1=LogisticRegression()

In [353]:
lr1.fit(x1train,y1train)

LogisticRegression()

In [354]:
predict_lr1=lr1.predict(x1test)

In [355]:
accuracy_score(predict_lr1,y1test)

0.9466054854520806

In [356]:
print(confusion_matrix(predict_lr1,y1test))
print(classification_report(predict_lr1,y1test))

[[8853  460]
 [  52  224]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97      9313
           1       0.33      0.81      0.47       276

    accuracy                           0.95      9589
   macro avg       0.66      0.88      0.72      9589
weighted avg       0.97      0.95      0.96      9589



In [357]:
svc1=SVC()

In [358]:
svc1.fit(x1train,y1train)
predict_svc1=svc1.predict(x1test)

In [359]:
print(accuracy_score(predict_svc1,y1test))
print(confusion_matrix(predict_svc1,y1test))
print(classification_report(predict_svc1,y1test))

0.9494212118051935
[[8852  432]
 [  53  252]]
              precision    recall  f1-score   support

           0       0.99      0.95      0.97      9284
           1       0.37      0.83      0.51       305

    accuracy                           0.95      9589
   macro avg       0.68      0.89      0.74      9589
weighted avg       0.97      0.95      0.96      9589



In [360]:
nb1=GaussianNB()

In [361]:
nb1.fit(x1train.toarray(),y1train)
predict_nb1=nb1.predict(x1test.toarray())

In [362]:
print(accuracy_score(predict_nb1,y1test))
print(confusion_matrix(predict_nb1,y1test))
print(classification_report(predict_nb1,y1test))

0.5567838147877776
[[4726   71]
 [4179  613]]
              precision    recall  f1-score   support

           0       0.53      0.99      0.69      4797
           1       0.90      0.13      0.22      4792

    accuracy                           0.56      9589
   macro avg       0.71      0.56      0.46      9589
weighted avg       0.71      0.56      0.46      9589



# Test Data

In [363]:
test_predict_lr=lr.predict(testtfidf_lemm)
test_predict_lr

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [364]:
test_predict_svc=svc.predict(testtfidf_lemm)
test_predict_svc

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [365]:
test_predict_nb=nb.predict(testtfidf_lemm.toarray())
test_predict_nb

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)